Modified workflow for tests

diff --git a/.github/workflows/terraform-azure-deploy.yml b/.github/workflows/terraform-azure-deploy.yml
--- a/.github/workflows/terraform-azure-deploy.yml
+++ b/.github/workflows/terraform-azure-deploy.yml
@@ -5,7 +5,7 @@ permissions: read-all
 on:
   push:
     branches:
-      - test
+      - tf-tests
     paths:
       - 'src/**'
       - '.github/**'
@@ -28,51 +28,52 @@ jobs:
     steps:
     - name: Shall execute set
       id: step1
-      run: echo "SHALL_EXECUTE=false" >> $GITHUB_OUTPUT
+      run: echo "SHALL_EXECUTE=true" >> $GITHUB_OUTPUT
 
-  IaC_Sec_Scan:
-    permissions:
-      contents: read
-      security-events: write
-      actions: read
+  # IaC_Sec_Scan:
+  #   permissions:
+  #     contents: read
+  #     security-events: write
+  #     actions: read
       
 
-    name: 'Checkov IaC Sec Scan'
-    if: ${{ needs.is_executed.outputs.output1 == 'true'}}
-    runs-on: ubuntu-latest
-    needs: is_executed
-    defaults:
-      run:
-        shell: bash
+  #   name: 'Checkov IaC Sec Scan'
+  #   if: ${{ needs.is_executed.outputs.output1 == 'true'}}
+  #   runs-on: ubuntu-latest
+  #   needs: is_executed
+  #   defaults:
+  #     run:
+  #       shell: bash
     
-    steps:
-      - uses: actions/checkout@v3
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - name: Checkov GitHub Action
-        uses: bridgecrewio/checkov-action@v12
-        with:
-          output_format: cli,sarif
-          output_file_path: console,results.sarif
+  #     - name: Checkov GitHub Action
+  #       uses: bridgecrewio/checkov-action@v12
+  #       with:
+  #         output_format: cli,sarif
+  #         output_file_path: console,results.sarif
       
-      - name: Upload SARIF file
-        uses: github/codeql-action/upload-sarif@v2
+  #     - name: Upload SARIF file
+  #       uses: github/codeql-action/upload-sarif@v2
 
-        if: success() || failure()
-        with:
-          sarif_file: results.sarif
+  #       if: success() || failure()
+  #       with:
+  #         sarif_file: results.sarif
     
   terraform-azure-deploy:
     name: 'Terraform Azure Deploy'
     if: ${{ needs.is_executed.outputs.output1 == 'true'}}
     runs-on: ubuntu-latest
-    needs: IaC_Sec_Scan
+    #needs: IaC_Sec_Scan
+    needs: is_executed
     defaults:
       run:
         shell: bash
 
     steps:
     - name: Shall execute set
-      run: SHALL_EXECUTE=false
+      run: SHALL_EXECUTE=true
       
     - name: Checkout
       uses: actions/checkout@v3
@@ -103,24 +104,24 @@ jobs:
       id: apply
       run: terraform -chdir=./src apply -auto-approve
 
-  destroy_infrastructure:
-    name: 'Terraform Azure Destroy'
-    runs-on: ubuntu-latest
-    needs: terraform-azure-deploy
-    defaults:
-      run:
-        shell: bash
+  # destroy_infrastructure:
+  #   name: 'Terraform Azure Destroy'
+  #   runs-on: ubuntu-latest
+  #   needs: terraform-azure-deploy
+  #   defaults:
+  #     run:
+  #       shell: bash
 
-    steps:
-    - name: Checkout
-      uses: actions/checkout@v3
-    - name: Terraform
-      uses: hashicorp/setup-terraform@v2
+  #   steps:
+  #   - name: Checkout
+  #     uses: actions/checkout@v3
+  #   - name: Terraform
+  #     uses: hashicorp/setup-terraform@v2
 
-    - name: 'Terraform Init'
-      id: init
-      run: terraform -chdir=./src init -backend-config="access_key=${{ secrets.TERRAFORM_STATE_STORAGE_ACCOUNT_KEY }}"
+  #   - name: 'Terraform Init'
+  #     id: init
+  #     run: terraform -chdir=./src init -backend-config="access_key=${{ secrets.TERRAFORM_STATE_STORAGE_ACCOUNT_KEY }}"
 
-    - name: Terraform Destroy
-      id: destroy
-      run: terraform -chdir=./src destroy -auto-approve
+  #   - name: Terraform Destroy
+  #     id: destroy
+  #     run: terraform -chdir=./src destroy -auto-approve
